apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: helm-guestbook
spec:
  project: prod
  source:
    repoURL: 'https://github.com/jeeeepp/argoCD.git'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: 'https://172.29.47.116:56381'
    namespace: '*'

