apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-yaml
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: guestbook

spec:
  project: dev
  source:
    repoURL: 'https://github.com/jeeeepp/argoCD.git'
    targetRevision: HEAD
    path: guestbook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev

