apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-yaml
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: guestbook

spec:
  project: prod
  source:
    repoURL: 'https://github.com/jeeeepp/argoCD.git'
    targetRevision: HEAD
    path: guestbook
  destination:
#    server: 'minikube-devops-116'
    server: 'https://172.29.47.116:56381'
    namespace: prod

